### ISSUE TITLE
Wrong styles for horizontal line

### ISSUE THREAD

**Issue by rudnitskih** [Stan0men/mate_academy_sep_2018#12]
![image](https://user-images.githubusercontent.com/8848858/46949103-e7ed0500-d088-11e8-8bb9-b1dfbf110560.png)

**Comment by Stan0men** [comment]
Fix it in previous commit

**Comment by rudnitskih** [comment]
`<hr>` has MacOS specific styles. Set `border: none;` to all `hr` elements
