### ISSUE TITLE
Wrong font

### ISSUE THREAD

**Issue by rudnitskih** [Stan0men/mate_academy_sep_2018#13]
![image](https://user-images.githubusercontent.com/8848858/46949204-4fa35000-d089-11e8-8513-1f558500e748.png)

**Comment by Stan0men** [comment]
On the psd file we have font-family: PTSans;
At my project I have font-family: 'PT Sans', sans-serif; 

Are there diferent? O_o

**Comment by rudnitskih** [comment]
You have fixed it one place, but I still see such button:

![image](https://user-images.githubusercontent.com/8848858/47024881-3c68b100-d16b-11e8-9f23-77969dfc5c05.png)

**Comment by rudnitskih** [comment]
Common, just check design and your implementation:
![image](https://user-images.githubusercontent.com/8848858/47071124-5fdb3c80-d1fb-11e8-9350-5d519a813a98.png)

Will discuss working with fonts on the lesson
