### ISSUE TITLE
Wrong fonts

### ISSUE THREAD

**Issue by rudnitskih** [Stan0men/mate_academy_sep_2018#24]
![image](https://user-images.githubusercontent.com/8848858/47778430-8c18b200-dcff-11e8-89f3-fc3e1fcb5663.png)

**Comment by Stan0men** [comment]
![02-11-2018 175853](https://user-images.githubusercontent.com/23480671/47926342-0183ae80-dec9-11e8-9339-4e491a9ba300.png)
