### ISSUE TITLE
Images should vertically centered

### ISSUE THREAD

**Issue by rudnitskih** [Stan0men/mate_academy_sep_2018#26]
![image](https://user-images.githubusercontent.com/8848858/47778758-30025d80-dd00-11e8-8438-96dde2ec8f59.png)

**Comment by Stan0men** [comment]
But I have it already 
![02-11-2018 174101](https://user-images.githubusercontent.com/23480671/47925309-86b99400-dec6-11e8-967b-018ee2543977.png)

Cloud has different height

**Comment by rudnitskih** [comment]
How you can see the cloud is not centered compare to comments and speedometer...

**Comment by Stan0men** [comment]
add class and margin-top to fix it 
.cloud {
  margin-top: 6px;
}
![05-11-2018 125140](https://user-images.githubusercontent.com/23480671/47993953-fff0fb00-e101-11e8-8ee1-5c6ea7b885ab.png)
