### ISSUE TITLE
Recheck margins between blocks

### ISSUE THREAD

**Issue by rudnitskih** [Stan0men/mate_academy_sep_2018#28]
![image](https://user-images.githubusercontent.com/8848858/47779010-cc2c6480-dd00-11e8-8349-cbeff48ba70d.png)

**Comment by Stan0men** [comment]
![02-11-2018 172942](https://user-images.githubusercontent.com/23480671/47924662-efa00c80-dec4-11e8-9e17-580f1c29ff8e.png)
