### ISSUE TITLE
Wrong proportions 

### ISSUE THREAD

**Issue by rudnitskih** [Stan0men/mate_academy_sep_2018#29]
Your:
![image](https://user-images.githubusercontent.com/8848858/47779087-f5e58b80-dd00-11e8-8069-ebd04f56f930.png)

Required:
![image](https://user-images.githubusercontent.com/8848858/47779062-e8c89c80-dd00-11e8-8df8-23553dcb841c.png)

**Comment by Stan0men** [comment]
![31-10-2018 135420](https://user-images.githubusercontent.com/23480671/47786486-96917680-dd14-11e8-8b5b-c7b8df538b8f.png)

**Comment by rudnitskih** [comment]
The image should be exactly two times bigger than block with text

**Comment by Stan0men** [comment]
![05-11-2018 113316](https://user-images.githubusercontent.com/23480671/47989845-0af25e00-e0f7-11e8-8070-4983168e2c5f.png)
