### ISSUE TITLE
Recheck block

### ISSUE THREAD

**Issue by rudnitskih** [Stan0men/mate_academy_sep_2018#31]
![image](https://user-images.githubusercontent.com/8848858/47779428-bff4d700-dd01-11e8-8b34-e54b4ffde0d4.png)

**Comment by Stan0men** [comment]
![02-11-2018 171928](https://user-images.githubusercontent.com/23480671/47923998-7eac2500-dec3-11e8-9d8b-f641903e2cec.png)

**Comment by Stan0men** [comment]
But, I dont know how to add icon for button

**Comment by rudnitskih** [comment]
You can put anything inside the button:)

**Comment by rudnitskih** [comment]
A button is bigger than input on mac:

![image](https://user-images.githubusercontent.com/8848858/47956124-809be400-dfa8-11e8-85be-4652b1702752.png)

**Comment by Stan0men** [comment]
![05-11-2018 110725](https://user-images.githubusercontent.com/23480671/47988519-7803f480-e0f3-11e8-86f4-d536543af4e1.png)

**Comment by rudnitskih** [comment]
So where is the icon, Sasha?)

**Comment by Stan0men** [comment]
Done 
![07-11-2018 123443](https://user-images.githubusercontent.com/23480671/48126346-8dab2280-e289-11e8-94df-63f9a4ca700b.png)
