### ISSUE TITLE
Social buttons should be interactive

### ISSUE THREAD

**Issue by rudnitskih** [Stan0men/mate_academy_sep_2018#32]
![image](https://user-images.githubusercontent.com/8848858/47779532-f6caed00-dd01-11e8-988c-e6b4e1044231.png)

**Comment by Stan0men** [comment]
![2018-10-31 14_36_00](https://user-images.githubusercontent.com/23480671/47785667-0fdb9a00-dd12-11e8-8505-68b27cafb5af.png)

**Comment by rudnitskih** [comment]
А можешь не такой эффект анимации сделать?)) Просто прозрачность уменьшать например:)

**Comment by Stan0men** [comment]
![05-11-2018 105653](https://user-images.githubusercontent.com/23480671/47987998-142cfc00-e0f2-11e8-98cf-a16ab1927bc6.png)

Втикнув правильно назвати комміт :(
