### ISSUE TITLE
Tablet issues

### ISSUE THREAD

**Issue by rudnitskih** [Stan0men/mate_academy_sep_2018#34]
1. make 2 columns of text. Add some horizontal padding to avoid text near the border
![image](https://user-images.githubusercontent.com/8848858/48122030-36a05000-e27f-11e8-93a4-15712fa695b1.png)

**Comment by rudnitskih** [comment]
Make a column with text and image equal width 
![image](https://user-images.githubusercontent.com/8848858/48122094-4e77d400-e27f-11e8-8b03-8a617201573d.png)

**Comment by rudnitskih** [comment]
Let's hide red line, on tablet and mobile. Also, add some padding in the bottom footer

![image](https://user-images.githubusercontent.com/8848858/48310059-7329bf80-e58f-11e8-996f-fbe6751131ec.png)

**Comment by rudnitskih** [comment]
![image](https://user-images.githubusercontent.com/8848858/48310190-ab7ecd00-e592-11e8-91a1-b061358f2273.png)

**Comment by Stan0men** [comment]
Dont know how to change commit message with git --amend but I have fixed this issueses

![11-11-2018 143625](https://user-images.githubusercontent.com/23480671/48312997-37a6e980-e5bf-11e8-84ce-773f0ad2e8af.png)
