### ISSUE TITLE
Mobile issues

### ISSUE THREAD

**Issue by rudnitskih** [Stan0men/mate_academy_sep_2018#35]
The main image should take all height on mobile as well
![image](https://user-images.githubusercontent.com/8848858/48122264-cba34900-e27f-11e8-9c26-97303f904dac.png)

**Comment by rudnitskih** [comment]
You can put links in one line:
![image](https://user-images.githubusercontent.com/8848858/48122522-6e5bc780-e280-11e8-9c3c-2e585b175c0f.png)

**Comment by rudnitskih** [comment]
Interesting bug for you:
white line in the right part on mobile

![image](https://user-images.githubusercontent.com/8848858/48122558-86334b80-e280-11e8-9c30-e48610687492.png)

**Comment by rudnitskih** [comment]
![image](https://user-images.githubusercontent.com/8848858/48122580-921f0d80-e280-11e8-9e05-8171a57765b9.png)

**Comment by Stan0men** [comment]
![08-11-2018 212833](https://user-images.githubusercontent.com/23480671/48222453-4746e800-e39d-11e8-8e72-81db36c51878.png)

**Comment by rudnitskih** [comment]
Please check 736px width:

![image](https://user-images.githubusercontent.com/8848858/48310083-0105aa80-e590-11e8-9951-a2fb8e52b06e.png)
