### ISSUE TITLE
Optional: image takes so big height on mobile

### ISSUE THREAD

**Issue by rudnitskih** [Stan0men/mate_academy_sep_2018#37]
Also center text vertically in the image block

![image](https://user-images.githubusercontent.com/8848858/48317715-de5eaa80-e5fe-11e8-8f74-db57b989f829.png)

**Comment by Stan0men** [comment]
![13-11-2018 171545](https://user-images.githubusercontent.com/23480671/48422670-d706e080-e767-11e8-8e32-9afec1cfa6da.png)

Img become to min-height:400px (two times smaller).
But I dont know how to center verticaly text.

 .big-picture__wrapper {
        vertical-align: middle;
    } 

isnt working
