### ISSUE TITLE
Wrong proportions for icons

### ISSUE THREAD

**Issue by rudnitskih** [Stan0men/mate_academy_sep_2018#5]
![image](https://user-images.githubusercontent.com/8848858/46935653-79964b80-d064-11e8-8d95-18824d319aa2.png)

**Comment by rudnitskih** [comment]
Still relevant:
![image](https://user-images.githubusercontent.com/8848858/46948980-85940480-d088-11e8-864d-43957ffeb1a1.png)

**Comment by Stan0men** [comment]
Styles from psd
background-color:  #50c3af;
width: 43px;
height: 31px;
---
My styles:
width: 43px;
height: 31px;

And what is wrong?

**Comment by rudnitskih** [comment]
Every image have different size!

![image](https://user-images.githubusercontent.com/8848858/47024276-08d95700-d16a-11e8-8068-310a16f57b46.png)

Just don't set width and height for image
